version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gnoluv
      - POSTGRES_PASSWORD=gnoluv
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres:
